spring:
  profiles:
    active: ${profile}
    group:
      local: "local"
      dev: "dev, datasource"
    include:
      - security
      - openai


cors-allowed-origins:
  https://team-play.netlify.app,
  http://localhost:8080,
  http://localhost:3000,
  http://localhost:5173
  
